// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwbU8c52f0jkwcBKwaisEwzy3ZmzVepbY',
    appId: '1:297183781947:web:eec33b744a649e52e3281e',
    messagingSenderId: '297183781947',
    projectId: 'fierbasetestproject',
    authDomain: 'fierbasetestproject.firebaseapp.com',
    storageBucket: 'fierbasetestproject.firebasestorage.app',
    measurementId: 'G-144PBP6Y8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbX6MKht3MJVKZQkz5TTYByF8OVvH9vuM',
    appId: '1:297183781947:android:36d24b9984284e7fe3281e',
    messagingSenderId: '297183781947',
    projectId: 'fierbasetestproject',
    storageBucket: 'fierbasetestproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhyfrxWD8t0v4Xx0D8aC8lOqB3ZZlbfB8',
    appId: '1:297183781947:ios:53b925f40c71ba98e3281e',
    messagingSenderId: '297183781947',
    projectId: 'fierbasetestproject',
    storageBucket: 'fierbasetestproject.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhyfrxWD8t0v4Xx0D8aC8lOqB3ZZlbfB8',
    appId: '1:297183781947:ios:53b925f40c71ba98e3281e',
    messagingSenderId: '297183781947',
    projectId: 'fierbasetestproject',
    storageBucket: 'fierbasetestproject.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );
}
